// commanders_list.js
// Auto-generated: Commander name, image path (from /commanders/ folder), and skill name

const commandersList = [
  { name: "Angla",               image: "commanders/Command2.jpg",   skillName: "Fleet EMT" },
  { name: "Leo",                 image: "commanders/Command14.jpg",  skillName: "Intimidate" },
  { name: "Natiya",              image: "commanders/Command10.jpg",  skillName: "First Strike" },
  { name: "Reggie",              image: "commanders/Command15.jpg",  skillName: "Paralyze" },
  { name: "Eveline",             image: "commanders/Command3.jpg",   skillName: "Find Weakness" },
  { name: "Stani",               image: "commanders/Command39.jpg",  skillName: "Interference" },
  { name: "Sofia",               image: "commanders/Command20.jpg",  skillName: "Maneuvering" },
  { name: "Jason",               image: "commanders/Command17.jpg",  skillName: "Save Energy" },
  { name: "Maletiz",             image: "commanders/Command40.jpg",  skillName: "Revenge" },
  { name: "Nick",                image: "commanders/Command9.jpg",   skillName: "Divine Intervention" },
  { name: "Jerome",              image: "commanders/Command1.jpg",   skillName: "Curse" },
  { name: "Aileen",              image: "commanders/Command29.jpg",  skillName: "Command Break" },
  { name: "Alicia",              image: "commanders/Command30.jpg",  skillName: "Inspiration" },
  { name: "Panis",               image: "commanders/Command27.jpg",  skillName: "Intercept" },
  { name: "Annata",              image: "commanders/Command28.jpg",  skillName: "Allied Support" },
  { name: "Kelly",               image: "commanders/Command24.jpg",  skillName: "Resourceful" },
  { name: "Rayllf",              image: "commanders/Command16.jpg",  skillName: "Armor Repair" },
  { name: "Donna",               image: "commanders/Command6.jpg",   skillName: "Defensive Intensity" },
  { name: "Sylva",               image: "commanders/Command4.jpg",   skillName: "Smash" },
  { name: "Gastaf",              image: "commanders/Command25.jpg",  skillName: "Deadly Strike" },
  { name: "Taude",               image: "commanders/Command0.jpg",   skillName: "Lucky Shot" },
  { name: "Wayne",               image: "commanders/Command5.jpg",   skillName: "Lucky Hit" },
  { name: "Sandora",             image: "commanders/Command7.jpg",   skillName: "Lucky Strike" },
  { name: "Raslin",              image: "commanders/Command31.jpg",  skillName: "Fear" },
  { name: "Maxius",              image: "commanders/Command12.jpg",  skillName: "Allied Strike" },
  { name: "Penni",               image: "commanders/Command23.jpg",  skillName: "Last Stand" },
  { name: "Motima",              image: "commanders/Command38.jpg",  skillName: "Accuracy" },
  { name: "Ringel",              image: "commanders/Command22.jpg",  skillName: "Ignite" },
  { name: "Anna",                image: "commanders/Command18.jpg",  skillName: "Pierce" },
  { name: "Linda",               image: "commanders/Command13.jpg",  skillName: "Broadside" },
  { name: "Heloyce",             image: "commanders/Command26.jpg",  skillName: "Stability" },
  { name: "Shaba",               image: "commanders/Command21.jpg",  skillName: "Allied Evasion" },
  { name: "Nora",                image: "commanders/Command8.jpg",   skillName: "Massacre" },
  { name: "Mantie",              image: "commanders/Command11.jpg",  skillName: "Command Strike" },
  { name: "Vinna",               image: "commanders/Command19.jpg",  skillName: "Cunning" },
  { name: "Singhri",             image: "commanders/Command32.jpg",  skillName: "Copycat" },
  { name: "Sylla",               image: "commanders/Command34.jpg",  skillName: "Fleet Link" },
  { name: "Rayo",                image: "commanders/Command36.jpg",  skillName: "Superior Command" },
  { name: "Bruce",               image: "commanders/Command35.jpg",  skillName: "Drain Supplies" },
  { name: "Marcus",              image: "commanders/Command33.jpg",  skillName: "Breakthrough" },
  { name: "Bart",                image: "commanders/Command37.jpg",  skillName: "Raid" },
  { name: "Lawrence",            image: "commanders/Command41.jpg",  skillName: "Ballistic Expertise" },
  { name: "Evi",                 image: "commanders/Command42.jpg",  skillName: "Directional Expertise" },
  { name: "Tyren",               image: "commanders/Command43.jpg",  skillName: "Missile Expertise" },
  { name: "Essido",              image: "commanders/Command44.jpg",  skillName: "Ship-based Expertise" },
  { name: "Robert",              image: "commanders/Command45.jpg",  skillName: "Lethality" },
  { name: "Dilira",              image: "commanders/Command46.jpg",  skillName: "Renewal" },
  { name: "Hellen",              image: "commanders/Command47.jpg",  skillName: "Rapid Reload" },
  { name: "Todd",                image: "commanders/Command48.jpg",  skillName: "Consecutive Strike" },
  { name: "Rafia",               image: "commanders/Command50.jpg",  skillName: "Stability Control" },
  { name: "Joseph",              image: "commanders/Command49.jpg",  skillName: "Vengeance" },
  { name: "Carlos",              image: "commanders/Command51.jpg",  skillName: "Fear Fiend" },
  { name: "Jakar",               image: "commanders/Command52.jpg",  skillName: "Aegis Shatter" },
  { name: "Rocky",               image: "commanders/Command53.jpg",  skillName: "Brutal Strength" },
  { name: "Andrew",              image: "commanders/Command54.jpg",  skillName: "Acrobatics" },
  { name: "Lynn",                image: "commanders/Command55.jpg",  skillName: "Victory Rush" },
  { name: "Miller",              image: "commanders/Command56.jpg",  skillName: "Pulverizer" },
  { name: "Victory Roar",        image: "commanders/Command57.jpg",  skillName: "Eradicate" },
  { name: "Rays of Destiny",     image: "commanders/Command58.jpg",  skillName: "Judgement" },
  { name: "Impending Doom",      image: "commanders/Command59.jpg",  skillName: "Insidious Infliction" },
  { name: "Desolate Prayers",    image: "commanders/Command60.jpg",  skillName: "Decaying Wane" },
  { name: "Deadly Duo",          image: "commanders/Command61.jpg",  skillName: "Crucifer Sweep" },
  { name: "Frontline Surge",     image: "commanders/Command62.jpg",  skillName: "Pioneer Prowl" },
  { name: "The Twin Torpedoes",  image: "commanders/Command63.jpg",  skillName: "Sharpshooter Storm" },
  { name: "Light and Darkness",  image: "commanders/Command64.jpg",  skillName: "Darkened Halo" },
  { name: "Kismet Beams",        image: "commanders/Command65.jpg",  skillName: "Supreme Smite" },
  { name: "Fatal Furies",        image: "commanders/Command66.jpg",  skillName: "Battering Barrage" },
  { name: "Indomitable Duo",     image: "commanders/Command67.jpg",  skillName: "Divine Barrier" },
  { name: "Death From Above",    image: "commanders/Command68.jpg",  skillName: "Death's Clutches" },
  { name: "Leech Lurkers",       image: "commanders/Command69.jpg",  skillName: "Covert Syphon" },
  { name: "Eternal Terrors",     image: "commanders/Command70.jpg",  skillName: "Battle Preparations" },
  { name: "Feral Raptors",       image: "commanders/Command71.jpg",  skillName: "Suicide Strike" },
  { name: "Iron Maidens",        image: "commanders/Command72.jpg",  skillName: "Fountain of Youth" },
  { name: "Fairy & Fiend",       image: "commanders/Command73.jpg",  skillName: "Double Whammy" },
  { name: "Suicidal Sirens",     image: "commanders/Command74.jpg",  skillName: "Risky Surge" },
  { name: "Wildfire",            image: "commanders/Command75.jpg",  skillName: "Trigger Happy" },
  { name: "Tactical Wizards",    image: "commanders/Command76.jpg",  skillName: "Bamboozle" },
  { name: "Fearmongers",         image: "commanders/Command77.jpg",  skillName: "Omen of Doom" },
  { name: "Pernicious Princes",  image: "commanders/Command78.jpg",  skillName: "Chain Vortex" },
  { name: "Summa Cum Laude",     image: "commanders/Command79.jpg",  skillName: "Verdant Force" },
  { name: "Carbuncle Cohort",    image: "commanders/Command80.jpg",  skillName: "Corrosive Coil" },
  { name: "Enduring Chorus",     image: "commanders/Command81.jpg",  skillName: "Renewed Faith" },
  { name: "The Ravagers",        image: "commanders/Command82.jpg",  skillName: "Smash & Grab" },
  { name: "Rex Scuta",           image: "commanders/Command83.jpg",  skillName: "Immunity" },
  { name: "Lurking Light",       image: "commanders/Command84.jpg",  skillName: "Phasing Halo" },
  { name: "Titan",               image: "commanders/Command85.jpg",  skillName: "Adaptive Mutation" },
  { name: "Eschaton Adventists", image: "commanders/Command86.jpg",  skillName: "Abject Humiliation" },
  { name: "Hand of Lelantos",    image: "commanders/Command87.jpg",  skillName: "Unseen Strike" },
  { name: "Hekatian Witnesses",  image: "commanders/Command88.jpg",  skillName: "Hekatian Edict" },
  { name: "Dopplegangers",       image: "commanders/Command89.jpg",  skillName: "Fierce Mutation" },
  { name: "Erebus Errants",      image: "commanders/Command90.jpg",  skillName: "Shadow Storm" },
  { name: "Cassius",             image: "commanders/Command91.jpg",  skillName: "Knockout Blow" },
  { name: "Bain",                image: "commanders/Command92.jpg",  skillName: "Reckoning" },
  { name: "Krina Klaus",         image: "commanders/Command93.jpg",  skillName: "Winter's Gift" },
  { name: "Homeric Hellions",    image: "commanders/Command94.jpg",  skillName: "Defiant Cry" },
  { name: "Winter Knights",      image: "commanders/Command95.jpg",  skillName: "Snow Blind" },
  { name: "Medusa",              image: "commanders/Command96.jpg",  skillName: "Gorgon Gaze" },
  { name: "Venus",               image: "commanders/Command97.jpg",  skillName: "Gift of Romance" },
  { name: "The Heartless Ones",  image: "commanders/Command98.jpg",  skillName: "Silence" },
  { name: "The Forsaken",        image: "commanders/Command99.jpg",  skillName: "Brainwash" },
  { name: "Callisto",            image: "commanders/Command100.jpg", skillName: "A Fire Rises" },
  { name: "Circe",               image: "commanders/Command101.jpg", skillName: "Hex" },
  { name: "The Pioneers",        image: "commanders/Command102.jpg", skillName: "Singularity" },
  { name: "Technomancers",       image: "commanders/Command103.jpg", skillName: "Null Field" },
  { name: "Queens of Blades",    image: "commanders/Command104.jpg", skillName: "Assimilation" },
  { name: "The Dictators",       image: "commanders/Command105.jpg", skillName: "Mutated Dominance" },
  { name: "Dune Enforcers",      image: "commanders/Command106.jpg", skillName: "Shadow Counter" },
  { name: "Slayer Bael",         image: "commanders/Command107.jpg", skillName: "Berserker Barrage" },
  { name: "Luna Silvestri",      image: "commanders/Command108.jpg", skillName: "Moon Blessing" },
  { name: "Chrome Dome",         image: "commanders/Command109.jpg", skillName: "10-Ton Strike" },
  { name: "Shadow Countess",     image: "commanders/Command110.jpg", skillName: "Shadow Cloak" },
  { name: "Murphy Lawson",       image: "commanders/Command111.jpg", skillName: "Rock 'N Roll" },
  { name: "Eva",                 image: "commanders/Command112.jpg", skillName: "Double Down" },
  { name: "Javal",               image: "commanders/Command113.jpg", skillName: "Adrenaline Surge" },
];

// Usage example:
// commandersList.find(c => c.name === "Sandora")
// => { name: "Sandora", image: "commanders/Command7.jpg", skillName: "Lucky Strike" }