// ════════════════════════════════════════════════════════════════════════
// guessCommanders.js — Commander data for the Commander Guess game
// Auto-generated from cmndrs.js (name, skillName, image base filename).
// Image files are expected under the "commanders/" folder, e.g.
// commanders/Command2.jpg — extension is auto-detected at runtime
// (tries .jpg, .png, .jpeg, .webp in order) so you don't need to rename files.
// Load this BEFORE guessGame.js.
// ════════════════════════════════════════════════════════════════════════
window.commandersList = [
  { name: "Angla", skillName: "Fleet EMT", image: "Command2", png: false },
  { name: "Leo", skillName: "Intimidate", image: "Command14", png: false },
  { name: "Natiya", skillName: "First Strike", image: "Command10", png: false },
  { name: "Reggie", skillName: "Paralyze", image: "Command15", png: false },
  { name: "Eveline", skillName: "Find Weakness", image: "Command3", png: false },
  { name: "Stani", skillName: "Interference", image: "Command39", png: false },
  { name: "Sofia", skillName: "Maneuvering", image: "Command20", png: false },
  { name: "Jason", skillName: "Save Energy", image: "Command17", png: false },
  { name: "Maletiz", skillName: "Revenge", image: "Command40", png: false },
  { name: "Nick", skillName: "Divine Intervention", image: "Command9", png: false },
  { name: "Jerome", skillName: "Curse", image: "Command1", png: false },
  { name: "Aileen", skillName: "Command Break", image: "Command29", png: false },
  { name: "Alicia", skillName: "Inspiration", image: "Command30", png: false },
  { name: "Panis", skillName: "Intercept", image: "Command27", png: false },
  { name: "Annata", skillName: "Allied Support", image: "Command28", png: false },
  { name: "Kelly", skillName: "Resourceful", image: "Command24", png: false },
  { name: "Rayllf", skillName: "Armor Repair", image: "Command16", png: false },
  { name: "Donna", skillName: "Defensive Intensity", image: "Command6", png: false },
  { name: "Sylva", skillName: "Smash", image: "Command4", png: false },
  { name: "Gastaf", skillName: "Deadly Strike", image: "Command25", png: false },
  { name: "Taude", skillName: "Lucky Shot", image: "Command0", png: false },
  { name: "Wayne", skillName: "Lucky Hit", image: "Command5", png: false },
  { name: "Sandora", skillName: "Lucky Strike", image: "Command7", png: false },
  { name: "Raslin", skillName: "Fear", image: "Command31", png: false },
  { name: "Maxius", skillName: "Allied Strike", image: "Command12", png: false },
  { name: "Penni", skillName: "Last Stand", image: "Command23", png: false },
  { name: "Motima", skillName: "Accuracy", image: "Command38", png: false },
  { name: "Ringel", skillName: "Ignite", image: "Command22", png: false },
  { name: "Anna", skillName: "Pierce", image: "Command18", png: false },
  { name: "Linda", skillName: "Broadside", image: "Command13", png: false },
  { name: "Heloyce", skillName: "Stability", image: "Command26", png: false },
  { name: "Shaba", skillName: "Allied Evasion", image: "Command21", png: false },
  { name: "Nora", skillName: "Massacre", image: "Command8", png: false },
  { name: "Mantie", skillName: "Command Strike", image: "Command11", png: false },
  { name: "Vinna", skillName: "Cunning", image: "Command19", png: false },
  { name: "Singhri", skillName: "Copycat", image: "Command32", png: false },
  { name: "Sylla", skillName: "Fleet Link", image: "Command34", png: false },
  { name: "Rayo", skillName: "Superior Command", image: "Command36", png: false },
  { name: "Bruce", skillName: "Drain Supplies", image: "Command35", png: false },
  { name: "Marcus", skillName: "Breakthrough", image: "Command33", png: false },
  { name: "Bart", skillName: "Raid", image: "Command37", png: false },
  { name: "Lawrence", skillName: "Ballistic Expertise", image: "Command41", png: false },
  { name: "Evi", skillName: "Directional Expertise", image: "Command42", png: false },
  { name: "Tyren", skillName: "Missile Expertise", image: "Command43", png: false },
  { name: "Essido", skillName: "Ship-based Expertise", image: "Command44", png: false },
  { name: "Robert", skillName: "Lethality", image: "Command45", png: false },
  { name: "Dilira", skillName: "Renewal", image: "Command46", png: false },
  { name: "Hellen", skillName: "Rapid Reload", image: "Command47", png: false },
  { name: "Todd", skillName: "Consecutive Strike", image: "Command48", png: false },
  { name: "Rafia", skillName: "Stability Control", image: "Command50", png: false },
  { name: "Joseph", skillName: "Vengeance", image: "Command49", png: false },
  { name: "Carlos", skillName: "Fear Fiend", image: "Command51", png: false },
  { name: "Jakar", skillName: "Aegis Shatter", image: "Command52", png: false },
  { name: "Rocky", skillName: "Brutal Strength", image: "Command53", png: false },
  { name: "Andrew", skillName: "Acrobatics", image: "Command54", png: false },
  { name: "Lynn", skillName: "Victory Rush", image: "Command55", png: false },
  { name: "Miller", skillName: "Pulverizer", image: "Command56", png: false },
  { name: "Victory Roar", skillName: "Eradicate", image: "Command57", png: false },
  { name: "Rays of Destiny", skillName: "Judgement", image: "Command58", png: false },
  { name: "Impending Doom", skillName: "Insidious Infliction", image: "Command59", png: false },
  { name: "Desolate Prayers", skillName: "Decaying Wane", image: "Command60", png: false },
  { name: "Deadly Duo", skillName: "Crucifer Sweep", image: "Command61", png: false },
  { name: "Frontline Surge", skillName: "Pioneer Prowl", image: "Command62", png: false },
  { name: "The Twin Torpedoes", skillName: "Sharpshooter Storm", image: "Command63", png: false },
  { name: "Light and Darkness", skillName: "Darkened Halo", image: "Command64", png: false },
  { name: "Kismet Beams", skillName: "Supreme Smite", image: "Command65", png: false },
  { name: "Fatal Furies", skillName: "Battering Barrage", image: "Command66", png: false },
  { name: "Indomitable Duo", skillName: "Divine Barrier", image: "Command67", png: false },
  { name: "Death From Above", skillName: "Death's Clutches", image: "Command68", png: false },
  { name: "Leech Lurkers", skillName: "Covert Syphon", image: "Command69", png: false },
  { name: "Eternal Terrors", skillName: "Battle Preparations", image: "Command70", png: false },
  { name: "Feral Raptors", skillName: "Suicide Strike", image: "Command71", png: false },
  { name: "Iron Maidens", skillName: "Fountain of Youth", image: "Command72", png: false },
  { name: "Fairy & Fiend", skillName: "Double Whammy", image: "Command73", png: false },
  { name: "Suicidal Sirens", skillName: "Risky Surge", image: "Command74", png: false },
  { name: "Wildfire", skillName: "Trigger Happy", image: "Command75", png: false },
  { name: "Tactical Wizards", skillName: "Bamboozle", image: "Command76", png: false },
  { name: "Fearmongers", skillName: "Omen of Doom", image: "Command77", png: false },
  { name: "Pernicious Princes", skillName: "Chain Vortex", image: "Command78", png: false },
  { name: "Summa Cum Laude", skillName: "Verdant Force", image: "Command79", png: false },
  { name: "Carbuncle Cohort", skillName: "Corrosive Coil", image: "Command80", png: false },
  { name: "Enduring Chorus", skillName: "Renewed Faith", image: "Command81", png: false },
  { name: "The Ravagers", skillName: "Smash & Grab", image: "Command82", png: false },
  { name: "Rex Scuta", skillName: "Immunity", image: "Command83", png: false },
  { name: "Lurking Light", skillName: "Phasing Halo", image: "Command84", png: false },
  { name: "Titan", skillName: "Adaptive Mutation", image: "Command85", png: false },
  { name: "Eschaton Adventists", skillName: "Abject Humiliation", image: "Command86", png: false },
  { name: "Hand of Lelantos", skillName: "Unseen Strike", image: "Command87", png: false },
  { name: "Hekatian Witnesses", skillName: "Hekatian Edict", image: "Command88", png: false },
  { name: "Dopplegangers", skillName: "Fierce Mutation", image: "Command89", png: false },
  { name: "Erebus Errants", skillName: "Shadow Storm", image: "Command90", png: false },
  { name: "Cassius", skillName: "Knockout Blow", image: "Command91", png: false },
  { name: "Bain", skillName: "Reckoning", image: "Command92", png: false },
  { name: "Krina Klaus", skillName: "Winter's Gift", image: "Command93", png: false },
  { name: "Homeric Hellions", skillName: "Defiant Cry", image: "Command94", png: false },
  { name: "Winter Knights", skillName: "Snow Blind", image: "Command95", png: false },
  { name: "Medusa", skillName: "Gorgon Gaze", image: "Command96", png: false },
  { name: "Venus", skillName: "Gift of Romance", image: "Command97", png: false },
  { name: "The Heartless Ones", skillName: "Silence", image: "Command98", png: false },
  { name: "The Forsaken", skillName: "Brainwash", image: "Command99", png: false },
  { name: "Circe", skillName: "Hex", image: "Command101", png: false },
  { name: "Callisto", skillName: "A Fire Rises", image: "Command100", png: false },
  { name: "The Pioneers", skillName: "Singularity", image: "Command102", png: false },
  { name: "Technomancers", skillName: "Null Field", image: "Command103", png: false },
  { name: "Queens of Blades", skillName: "Assimilation", image: "Command104", png: false },
  { name: "The Dictators", skillName: "Mutated Dominance", image: "Command105", png: false },
  { name: "Dune Enforcers", skillName: "Shadow Counter", image: "Command106", png: false },
  { name: "Slayer Bael", skillName: "Berserker Barrage", image: "Command107", png: false },
  { name: "Luna Silvestri", skillName: "Moon Blessing", image: "Command108", png: false },
  { name: "Chrome Dome", skillName: "10-Ton Strike", image: "Command109", png: false },
  { name: "Shadow Countess", skillName: "Shadow Cloak", image: "Command110", png: false },
  { name: "Murphy Lawson", skillName: "Rock 'N Roll", image: "Command111", png: false },
  { name: "Eva", skillName: "Double Down", image: "Command112", png: true },
  { name: "Javal", skillName: "Adrenaline Surge", image: "Command113", png: true },
];