// ══════════════════════════════════════════════════════
// COMMANDER MCQ DATABASE — mcqdb.js
// Open Galaxy · Constellation Hub
// Add new questions here; they are picked randomly at
// quiz creation time. Each entry needs:
//   question : string
//   options  : array of 4 strings
//   answer   : string (must exactly match one option)
// ══════════════════════════════════════════════════════

const QUIZ_BANK = [

  // ── STATS AFFECTING ABILITIES ──────────────────────
  {question:"What stats affect Angla's 'Fleet EMT' ability?",options:["Accuracy + Dodge","Dodge + Electron","Dodge","Speed"],answer:"Dodge"},
  {question:"What stats affect Leo's 'Intimidate' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Electron"},
  {question:"What stats affect Natiya's 'First Strike' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Reggie's 'Paralyze' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Electron"},
  {question:"What stats affect Eveline's 'Find Weakness' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Stani's 'Interference' ability?",options:["Accuracy and Speed","Accuracy and Electron","Dodge and Electron","Speed and Electron"],answer:"Accuracy and Electron"},
  {question:"What stats affect Sofia's 'Maneuvering' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Jason's 'Save Energy' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Electron"},
  {question:"What stats affect Maletiz's 'Revenge' ability?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Dodge and Electron"},
  {question:"What stats affect Nick's 'Divine Intervention' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Dodge"},
  {question:"What stats affect Jerome's 'Curse' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Aileen's 'Command Break' ability?",options:["Accuracy and Speed","Electron and Speed","Dodge and Electron","Accuracy and Electron"],answer:"Electron and Speed"},
  {question:"What stats affect Alicia's 'Inspiration' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Panis' 'Intercept' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Electron"},
  {question:"What stats affect Annata's 'Allied Support' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Kelly's 'Resourceful' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Rayllf's 'Armor Repair' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Donna's 'Defensive Intensity' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect Gastaf's 'Deadly Strike' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Taude's 'Lucky Shot' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Wayne's 'Lucky Hit' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Sandora's 'Lucky Strike' ability?",options:["Accuracy and Speed","Electron and Speed","Dodge and Electron","Accuracy and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect Raslin's 'Fear' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Electron"},
  {question:"What stats affect Maxius' 'Allied Strike' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Penni's 'Last Stand' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Shaba's 'Allied Evasion' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Dodge"},
  {question:"What stats affect Nora's 'Massacre' ability?",options:["Accuracy and Speed","Accuracy and Dodge","Dodge and Electron","Accuracy and Electron"],answer:"Accuracy and Dodge"},
  {question:"What stats affect Mantie's 'Command Strike' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Dodge"},
  {question:"What stats affect Lawrence's short range trajectories ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Evi's 'Directional Expertise' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect Todd's 'Consecutive Strike' ability?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect 'Rays of Destiny' (Sandora + Maletiz) skill?",options:["Accuracy only","Affected by all 4 attributes","Dodge and Electron","Speed and Electron"],answer:"Affected by all 4 attributes"},
  {question:"What stats affect 'Impending Doom' (Nick + Jerome) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Dodge and Electron"},
  {question:"What stats affect 'Desolate Prayers' (Aileen + Stani) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect 'Deadly Duo' (Anna + Linda) skill?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect 'Frontline Surge' (Sofia + Lynn) skill?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect 'The Twin Torpedoes' (Gastaf + Todd) skill?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Accuracy"},
  {question:"What stats affect 'Light and Darkness' (Annata + Leo) skill?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Speed"},
  {question:"What stats affect 'Kismet Beams' (Sandora + Wayne) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect 'Fatal Furies' (Wayne + Marcus) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect 'Indomitable Duo' (Heloyce + Andrew) skill?",options:["Accuracy","Electron","Dodge","Speed"],answer:"Dodge"},
  {question:"What stats affect 'Death From Above' (Rayo + Robert) skill?",options:["Accuracy only","Affected by all 4 attributes","Dodge and Electron","Speed and Electron"],answer:"Affected by all 4 attributes"},
  {question:"What stats affect 'Leech Lurkers' (Bart + Leo) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect 'Eternal Terrors' (Reggie + Hellen) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Electron"},
  {question:"What stats affect 'Feral Raptors' (Wayne + Penni) skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect 'Iron Maidens' (Dilira + Rafia) skill?",options:["Accuracy and Speed","Speed and Dodge","Accuracy and Electron","Speed and Electron"],answer:"Speed and Dodge"},
  {question:"What stats affect 'Fairy & Fiend' skill?",options:["Accuracy and Speed","Dodge and Electron","Accuracy and Electron","Speed and Electron"],answer:"Accuracy and Speed"},
  {question:"What stats affect Murphy Lawson's 'Rock N Roll' skill?",options:["Accuracy and Speed","Dodge and Speed","Accuracy and Electron","Speed and Electron"],answer:"Dodge and Speed"},
  {question:"What stats affect Javal's 'Adrenaline Surge' ability?",options:["Accuracy only","Affected by all 4 stats","Dodge and Electron","Speed and Electron"],answer:"Affected by all 4 stats"},

  // ── SKILL NAMES ────────────────────────────────────
  {question:"What is the name of Leo's signature skill?",options:["Fear","Intimidate","Curse","Interference"],answer:"Intimidate"},
  {question:"What is the name of Natiya's signature skill?",options:["First Strike","Maneuvering","Lucky Shot","Fleet EMT"],answer:"First Strike"},
  {question:"What is the name of Reggie's signature skill?",options:["Interference","Paralyze","Curse","Command Break"],answer:"Paralyze"},
  {question:"What is the name of Stani's signature skill?",options:["Paralyze","Curse","Interference","Fear"],answer:"Interference"},
  {question:"What is the name of Sofia's signature skill?",options:["First Strike","Maneuvering","Save Energy","Allied Strike"],answer:"Maneuvering"},
  {question:"What is the name of Jason's signature skill?",options:["Save Energy","Armor Repair","Resourceful","Allied Support"],answer:"Save Energy"},
  {question:"What is the name of Maletiz's signature skill?",options:["Divine Intervention","Revenge","Last Stand","Massacre"],answer:"Revenge"},
  {question:"What is the name of Nick's signature skill?",options:["Revenge","Divine Intervention","Lucky Strike","Allied Evasion"],answer:"Divine Intervention"},
  {question:"What is the name of Jerome's signature skill?",options:["Fear","Intimidate","Curse","Interference"],answer:"Curse"},
  {question:"What is the name of Aileen's signature skill?",options:["Command Break","Last Stand","Massacre","Command Strike"],answer:"Command Break"},
  {question:"What is the name of Alicia's signature skill?",options:["Allied Strike","Inspiration","Allied Support","Lucky Shot"],answer:"Inspiration"},
  {question:"What is the name of Panis' signature skill?",options:["Armor Repair","Defensive Intensity","Intercept","Stability Control"],answer:"Intercept"},
  {question:"What is the name of Annata's signature skill?",options:["Allied Support","Resourceful","Armor Repair","Defensive Intensity"],answer:"Allied Support"},
  {question:"What is the name of Kelly's signature skill?",options:["Allied Support","Resourceful","Armor Repair","Defensive Intensity"],answer:"Resourceful"},
  {question:"What is the name of Rayllf's signature skill?",options:["Allied Support","Resourceful","Armor Repair","Defensive Intensity"],answer:"Armor Repair"},
  {question:"What is the name of Donna's signature skill?",options:["Allied Support","Resourceful","Armor Repair","Defensive Intensity"],answer:"Defensive Intensity"},
  {question:"What is the name of Sylva's signature skill?",options:["Smash","Deadly Strike","Lucky Shot","Lucky Hit"],answer:"Smash"},
  {question:"What is the name of Gastaf's signature skill?",options:["Smash","Deadly Strike","Lucky Shot","Lucky Hit"],answer:"Deadly Strike"},
  {question:"What is the name of Taude's signature skill?",options:["Smash","Deadly Strike","Lucky Shot","Lucky Hit"],answer:"Lucky Shot"},
  {question:"What is the name of Wayne's signature skill?",options:["Smash","Deadly Strike","Lucky Shot","Lucky Hit"],answer:"Lucky Hit"},
  {question:"What is the name of Sandora's signature skill?",options:["Lucky Strike","Massacre","Last Stand","Allied Strike"],answer:"Lucky Strike"},
  {question:"What is the name of Raslin's signature skill?",options:["Intimidate","Curse","Fear","Interference"],answer:"Fear"},
  {question:"What is the name of Maxius' signature skill?",options:["Inspiration","Allied Strike","Allied Support","Lucky Shot"],answer:"Allied Strike"},
  {question:"What is the name of Penni's signature skill?",options:["Last Stand","Massacre","Command Strike","Revenge"],answer:"Last Stand"},
  {question:"What is the name of Shaba's signature skill?",options:["Allied Evasion","Divine Intervention","Maneuvering","First Strike"],answer:"Allied Evasion"},
  {question:"What is the name of Nora's signature skill?",options:["Last Stand","Massacre","Command Strike","Revenge"],answer:"Massacre"},
  {question:"What is the name of Mantie's signature skill?",options:["Last Stand","Massacre","Command Strike","Revenge"],answer:"Command Strike"},
  {question:"What is the name of Evi's signature skill?",options:["Directional Expertise","Consecutive Strike","Stability Control","Adrenaline Surge"],answer:"Directional Expertise"},
  {question:"What is the name of Todd's signature skill?",options:["Directional Expertise","Consecutive Strike","Stability Control","Adrenaline Surge"],answer:"Consecutive Strike"},
  {question:"What is the name of Rafia's signature skill?",options:["Directional Expertise","Consecutive Strike","Stability Control","Adrenaline Surge"],answer:"Stability Control"},
  {question:"What is the name of Javal's signature skill?",options:["Directional Expertise","Consecutive Strike","Stability Control","Adrenaline Surge"],answer:"Adrenaline Surge"},
  {question:"What is the name of Murphy Lawson's signature skill?",options:["Rock 'N Roll","Adrenaline Surge","Double Whammy","Eradicate"],answer:"Rock 'N Roll"},
  // ── COMBO SKILL NAMES ─────────────────────────────
  {question:"What is the skill name for the combo commander 'Rays of Destiny'?",options:["Judgement","Insidious Infliction","Decaying Wane","Crucifer Sweep"],answer:"Judgement"},
  {question:"What is the skill name for the combo commander 'Impending Doom'?",options:["Judgement","Insidious Infliction","Decaying Wane","Crucifer Sweep"],answer:"Insidious Infliction"},
  {question:"What is the skill name for the combo commander 'Desolate Prayers'?",options:["Judgement","Insidious Infliction","Decaying Wane","Crucifer Sweep"],answer:"Decaying Wane"},
  {question:"What is the skill name for 'Deadly Duo' (Anna + Linda)?",options:["Judgement","Insidious Infliction","Decaying Wane","Crucifer Sweep"],answer:"Crucifer Sweep"},
  {question:"What is the skill name for 'Frontline Surge' (Sofia + Lynn)?",options:["Pioneer Prowl","Sharpshooter Storm","Darkened Halo","Supreme Smite"],answer:"Pioneer Prowl"},
  {question:"What is the skill name for 'The Twin Torpedoes' (Gastaf + Todd)?",options:["Pioneer Prowl","Sharpshooter Storm","Darkened Halo","Supreme Smite"],answer:"Sharpshooter Storm"},
  {question:"What is the skill name for 'Light and Darkness' (Annata + Leo)?",options:["Pioneer Prowl","Sharpshooter Storm","Darkened Halo","Supreme Smite"],answer:"Darkened Halo"},
  {question:"What is the skill name for 'Kismet Beams' (Sandora + Wayne)?",options:["Pioneer Prowl","Sharpshooter Storm","Darkened Halo","Supreme Smite"],answer:"Supreme Smite"},
  {question:"What is the skill name for 'Fatal Furies' (Wayne + Marcus)?",options:["Battering Barrage","Divine Barrier","Death's Clutches","Covert Syphon"],answer:"Battering Barrage"},
  {question:"What is the skill name for 'Indomitable Duo' (Heloyce + Andrew)?",options:["Battering Barrage","Divine Barrier","Death's Clutches","Covert Syphon"],answer:"Divine Barrier"},
  {question:"What is the skill name for 'Death From Above' (Rayo + Robert)?",options:["Battering Barrage","Divine Barrier","Death's Clutches","Covert Syphon"],answer:"Death's Clutches"},
  {question:"What is the skill name for 'Leech Lurkers' (Bart + Leo)?",options:["Battering Barrage","Divine Barrier","Death's Clutches","Covert Syphon"],answer:"Covert Syphon"},
  {question:"What is the skill name for 'Eternal Terrors' (Reggie + Hellen)?",options:["Battle Preparations","Suicide Strike","Fountain of Youth","Double Whammy"],answer:"Battle Preparations"},
  {question:"What is the skill name for 'Feral Raptors' (Wayne + Penni)?",options:["Battle Preparations","Suicide Strike","Fountain of Youth","Double Whammy"],answer:"Suicide Strike"},
  {question:"What is the skill name for 'Iron Maidens' (Dilira + Rafia)?",options:["Battle Preparations","Suicide Strike","Fountain of Youth","Double Whammy"],answer:"Fountain of Youth"},
  {question:"What is the skill name for 'Fairy & Fiend'?",options:["Battle Preparations","Suicide Strike","Fountain of Youth","Double Whammy"],answer:"Double Whammy"},
  // ── ABILITY MECHANICS ────────────────────────────
  {question:"What is the steps range limit for Leo's defensive reduction area of effect?",options:["1 step","2 steps","3 steps","4 steps"],answer:"2 steps"},
  {question:"By how many steps can Sofia move when her Maneuvering triggers?",options:["1 space","2 spaces","3 spaces","4 spaces"],answer:"3 spaces"},
  {question:"What fuel item does Jason's 'Save Energy' nullify during engagement?",options:["Dark Matter core units","He3 fuel cells","Plasma elements","Anti-matter cells"],answer:"He3 fuel cells"},
  {question:"What does Maletiz's 'Revenge' do upon absorbing damage?",options:["Reflects it back to the attacker","Converts it to shield values","Shares it among nearby spaces","Neutralizes enemy commander stats"],answer:"Reflects it back to the attacker"},
  {question:"What benefit does Nick's 'Divine Intervention' yield when active?",options:["A chance to avoid damage","Instantly double current speed","Bypasses all shielding profiles","Inflicts curse stacks"],answer:"A chance to avoid damage"},
  {question:"By what percentage does Jerome's 'Curse' increase incoming damage?",options:["5% stackable","10% stackable","20% non-stackable","50% fixed"],answer:"10% stackable"},
  {question:"To what value does Aileen's 'Command Break' drop hostile commander stats?",options:["Halved","Reduced by 50 points","Dropped to 0","Unchanged"],answer:"Dropped to 0"},
  {question:"By what percentage does Alicia's 'Inspiration' increase adjacent ship damage?",options:["10%","20%","30%","50%"],answer:"30%"},
  {question:"What maximum damage multiplier does Sylva's 'Smash' apply against fortresses?",options:["1.5x","2.0x","2.5x","3.0x"],answer:"2.5x"},
  {question:"What type of target does Sylva's damage multiplier focus on?",options:["Carrier ships","A fortress","Frigate clusters","All dynamic units"],answer:"A fortress"},
  {question:"What does Gastaf's 'Deadly Strike' passive amplify?",options:["Critical strikes","Double evasion loops","Formation tracking","Recoil reduction rates"],answer:"Critical strikes"},
  {question:"By how much does Taude's 'Lucky Shot' improve destruction chance?",options:["25%","30%","50%","100%"],answer:"50%"},
  {question:"What damage factor does Wayne's 'Lucky Hit' apply on deployment?",options:["Double damage","Triple damage","Quadruple damage","1.5x enhancement"],answer:"Double damage"},
  {question:"What scattering damage percentage does Sandora's 'Lucky Strike' apply?",options:["15%","30%","50%","100%"],answer:"30%"},
  {question:"By what ratio does Raslin's 'Fear' reduce enemy attack capability?",options:["10%","25%","50%","75%"],answer:"50%"},
  {question:"By how much does Maxius' 'Allied Strike' boost friendly accuracy?",options:["2 points","5 points","8 points","10 points"],answer:"5 points"},
  {question:"What range does Maxius' 'Allied Strike' accuracy boost cover?",options:["2 spaces","4 spaces","6 spaces","All spaces"],answer:"4 spaces"},
  {question:"What damage multiplier does Penni's 'Last Stand' inflict?",options:["Double damage","Triple damage","Quadruple damage","Five-fold damage"],answer:"Triple damage"},
  {question:"What self-damage penalty does Penni's 'Last Stand' impose?",options:["3%","5%","10%","20%"],answer:"10%"},
  {question:"By how much does Shaba's 'Allied Evasion' boost friendly dodge within 4 spaces?",options:["2 points","5 points","10 points","15 points"],answer:"5 points"},
  {question:"Is Shaba's dodge boost stackable over multiple rounds?",options:["Yes (stackable)","No (non-stackable)","Only once per game","Only round one"],answer:"Yes (stackable)"},
  {question:"How many times per round can Nora's 'Massacre' be triggered?",options:["Once per round","Twice per round","Three times","Unlimited"],answer:"Once per round"},
  {question:"What self-fatality rate increase does Mantie's 'Command Strike' carry?",options:["1%","3%","5%","10%"],answer:"3%"},
  {question:"What weapon class does Evi's 'Directional Expertise' amplify?",options:["Ballistic Weapons","Directional Weapons","Missile Weapons","Carrier Fighters"],answer:"Directional Weapons"},
  {question:"What maximum attack frequency can Todd's 'Consecutive Strike' trigger?",options:["Attacking the target twice","Triple attack actions","Attacking all targets once","Counter-attacking out of turn"],answer:"Attacking the target twice"},
  {question:"What condition maximises Rafia's 'Stability Control' ship defense?",options:["Her 4 stats exceed the opposing commander's","Target shields are broken","Round timer exceeds 5 turns","Accuracy stat reaches zero"],answer:"Her 4 stats exceed the opposing commander's"},
  {question:"What extreme attack power boost does Murphy Lawson's 'Rock N Roll' apply?",options:["200%","300%","500%","800%"],answer:"800%"},
  {question:"When does enemy fleet defense recover after Murphy Lawson zeros it?",options:["At the end of the round","After 2 turns","Never","Instantly upon next hit"],answer:"At the end of the round"},
  {question:"What unique bypass mechanic defines Javal's 'Adrenaline Surge'?",options:["Bypass the enemy commander's ability effects","Ignore ship armor ratings","Avoid terrain step tracking","Bypass weapon alignment requirements"],answer:"Bypass the enemy commander's ability effects"},
  // ── COMBO SKILL MECHANICS ─────────────────────────
  {question:"What does the fusion skill 'Judgement' combine?",options:["30% Scattering damage and absorbed damage reflection","Bypassing all layout frameworks","Halving enemy module integrity","Setting map boundaries to zero"],answer:"30% Scattering damage and absorbed damage reflection"},
  {question:"What dual utilities does 'Insidious Infliction' provide?",options:["Chance to avoid damage + inflicts a 10% stackable damage curse","Triple attack loops + recoil penalty","Speed adjustments + fuel optimization","Complete range expansions"],answer:"Chance to avoid damage + inflicts a 10% stackable damage curse"},
  {question:"What side-effect comes alongside 'Decaying Wane's' stat wipe?",options:["The target is immobilized next round","Accepting 10% structural recoil","Shield caps drop 50%","Losing 3 spaces of movement"],answer:"The target is immobilized next round"},
  {question:"What scattering and piercing ratios does 'Crucifer Sweep' apply?",options:["50% Scattering and 40% Piercing","10% each side","30% Scattering and 100% Piercing","Double damage flat"],answer:"50% Scattering and 40% Piercing"},
  {question:"By how much does 'Pioneer Prowl' increase attack per space moved?",options:["2% per space","5% per space","10% per space","20% per space"],answer:"10% per space"},
  {question:"What does 'Sharpshooter Storm' bundle together?",options:["Increases critical strike rate and grants a chance to attack twice","Wipes enemy defenses and hits three targets","Reduces map footprint sizes","Triggers fuel conversions instantly"],answer:"Increases critical strike rate and grants a chance to attack twice"},
  {question:"What spatial limit applies to 'Darkened Halo's' friendly support?",options:["2 steps","3 steps","4 steps","5 steps"],answer:"4 steps"},
  {question:"What multi-ship damage does 'Supreme Smite' deliver?",options:["Double damage and 30% Scattering to all enemy ships","Triple damage against single fortress","Nullifying all stat attributes","Reflecting damage back symmetrically"],answer:"Double damage and 30% Scattering to all enemy ships"},
  {question:"What defensive systems does 'Battering Barrage' bypass?",options:["Target's Shield, Modules, and Stability","Baseline velocity matrices","Fuel optimization mechanics","Dodge values"],answer:"Target's Shield, Modules, and Stability"},
  {question:"Under what condition does 'Divine Barrier' neutralize scattering penalties?",options:["Dodge rating exceeds enemy Accuracy rating","Aim index values double opponents","Priority tracking reaches 100","Fuel cells are stable"],answer:"Dodge rating exceeds enemy Accuracy rating"},
  {question:"What happens when 'Death From Above' triggers with dominant base stats?",options:["Adjacent ships deal double attacks or crits and enemy abilities are nullified","All enemy shields are fully drained","Target units are pushed back 3 spaces","Recoil values drop to zero"],answer:"Adjacent ships deal double attacks or crits and enemy abilities are nullified"},
  {question:"By how much does 'Covert Syphon' increase structural attack power for one round?",options:["5%","10%","15%","25%"],answer:"15%"},
  {question:"What instant reset does 'Battle Preparations' offer upon attack validation?",options:["Instantly reload all weapons and prevent enemy abilities","Repair all module hulls to max","Double movement allowance for two steps","Wipe active curse layouts"],answer:"Instantly reload all weapons and prevent enemy abilities"},
  {question:"What extreme damage factor defines 'Suicide Strike's' offense risk?",options:["2x","3x","5x","6x"],answer:"6x"},
  {question:"What twin damage ratios apply under 'Crucifer Sweep'?",options:["50% Scattering Damage and 40% Piercing damage","10% baseline each side","30% Scattering and 100% Piercing","Double damage flat variables"],answer:"50% Scattering Damage and 40% Piercing damage"},
  {question:"What does 'Supreme Smite' deliver to the enemy fleet?",options:["Double damage and 30% Scattering damage to all ships in an enemy fleet","Triple damage against single fortress nodes","Nullifying stat attributes down to zero","Reflecting damage symmetrically back"],answer:"Double damage and 30% Scattering damage to all ships in an enemy fleet"},
  {question:"What systems does 'Battering Barrage' bypass?",options:["Target's Shield, Modules, and Stability","Baseline velocity matrices","Fuel optimization mechanics","Dodge values"],answer:"Target's Shield, Modules, and Stability"},
  {question:"Under what condition does 'Divine Barrier' neutralize scattering penalties?",options:["Dodge rating is higher than the enemy commander's Accuracy rating","Aim index values double opponent totals","Priority tracking stats reach 100","Fuel cells parameter totals are stable"],answer:"Dodge rating is higher than the enemy commander's Accuracy rating"},
  {question:"What extreme amplification defines 'Suicide Strike's' offense risk?",options:["2x damage","3x damage","5x damage","6x damage"],answer:"6x damage"},
  // ── LORE & BIOGRAPHY ─────────────────────────────
  {question:"What rumor surrounds Angla's childhood?",options:["Born on a pirate station","Her DNA was modified and strengthened when she was young","Master mathematician at an early age","Raised by space wolves"],answer:"Her DNA was modified and strengthened when she was young"},
  {question:"What physical adversity does Leo cope with?",options:["An unknown disease requiring strong painkillers","A cybernetic replacement matrix flaw","Blindness from space radiation","Memory loss after a pirate attack"],answer:"An unknown disease requiring strong painkillers"},
  {question:"From which institution did Natiya graduate as top pilot?",options:["Galactic Weapon College","Galaxy Command College","Supreme Science Academy","Command College"],answer:"Command College"},
  {question:"What professional background does Reggie possess?",options:["Chemical engineer","Electronic engineer","Mechanical repairman","Astrophysicist"],answer:"Electronic engineer"},
  {question:"What personality traits do close friends assign to Eveline?",options:["Arrogant and success-driven","Humble, hardworking, with exceptionally strong willpower","Mysterious and unpredictable","Reckless and frantic"],answer:"Humble, hardworking, with exceptionally strong willpower"},
  {question:"What subject did Stani master to manipulate battle signals?",options:["Ballistic trajectories and math","Electronic impulses and circuitry","Energy systems conversion","Biological and chemical warfare"],answer:"Electronic impulses and circuitry"},
  {question:"What low-level job did Sofia start her career under?",options:["Common mechanic","Fighter pilot intern","Data network analyst","Cargo ship driver"],answer:"Common mechanic"},
  {question:"What energy breakthrough did Jason invent?",options:["Anti-matter warp frameworks","Energy Source Conversion Technology","He3 compression pipelines","Plasma shielding matrices"],answer:"Energy Source Conversion Technology"},
  {question:"Where did Maletiz begin his early development?",options:["A den of ferocious wolves","The supreme science academy","A corporate training cruiser","An isolated mining asteroid station"],answer:"A den of ferocious wolves"},
  {question:"What is Jerome's historical nickname?",options:["The Brilliant Strategist","The Witchdoctor","Black Hole","Twin Hero"],answer:"The Witchdoctor"},
  {question:"What task earned Aileen her galaxy reputation?",options:["An accomplished pirate slayer","Inventing trajectory equations in her head","Governor of a remote fortress colony","Surviving a wolf clan den"],answer:"An accomplished pirate slayer"},
  {question:"What gossip surrounds Alicia's career promotions?",options:["She bribed high admirals","Her predecessors were removed","Top of class by luck","Used alien technologies"],answer:"Her predecessors were removed"},
  {question:"What faction does Panis hold deep contempt toward?",options:["The Alliance Fleet","Pirates that turn over a new leaf","The Command College leadership","Chemical warfare researchers"],answer:"Pirates that turn over a new leaf"},
  {question:"What skill is Annata celebrated for?",options:["Master technician and expert in repairs","Calculating complex ballistic models","Managing fuel sourcing","Infiltrating enemy lines undetected"],answer:"Master technician and expert in repairs"},
  {question:"What cause did Kelly passionately advocate before declaring war on pirates?",options:["Galactic peace","Weapon trade expansion","Carrier ship research","Wolf clan territory sovereignty"],answer:"Galactic peace"},
  {question:"What tactical mindset guides Rayllf's combat strategy?",options:["A strong defense leads to greater offense","Sacrificing ships at any cost","First strike sets absolute victory","Relying on pure luck"],answer:"A strong defense leads to greater offense"},
  {question:"What core purpose guided Donna's technology focus?",options:["Protecting people from the scum of the universe via defensive tech","Maximizing ballistic delivery systems","Tracking space wolf movement","Avoiding close combat via range modifications"],answer:"Protecting people from the scum of the universe via defensive tech"},
  {question:"What public sector role kick-started Sylva's military career?",options:["A regional governor","A command college assistant advisor","An electronic engineering apprentice","A commercial cargo ship pilot"],answer:"A regional governor"},
  {question:"What distinct fashion item is Gastaf famous for wearing?",options:["A silver battle helmet","Stylish sunglasses","A heavy armor flight jacket","A wolf clan talisman"],answer:"Stylish sunglasses"},
  {question:"What undesirable personality trait defines Taude despite his success?",options:["Insufferably arrogant","Panicky under fire","Completely emotionless","Monstrous visage anxiety"],answer:"Insufferably arrogant"},
  {question:"What core talent enables Wayne to boost his crew's performance?",options:["Natural leadership abilities","Advanced mathematical tracking","Wolf pack instinct","Painkiller chemical immunities"],answer:"Natural leadership abilities"},
  {question:"What key trait defines Sandora's behavior under active fire?",options:["Calmness under fire","Panic-induced weapon launches","Arrogant boasting over channels","Emotionless cold expressions"],answer:"Calmness under fire"},
  {question:"What secondary academic role did Raslin fill at his Alma Mater?",options:["Technical adviser to the college","Regional planetary governor","Medical research director","Chief security admiral"],answer:"Technical adviser to the college"},
  {question:"What ancestral background did Maxius descend from?",options:["One of the wealthiest families in the galaxy","An isolated mining crew faction","A line of chemical weapon specialists","A pirate fleet syndicate family"],answer:"One of the wealthiest families in the galaxy"},
  {question:"What animal-themed nickname matches Penni's profile?",options:["Wildcat","Space Wolf","Iron Maiden","Feral Raptor"],answer:"Wildcat"},
  {question:"How old was Shaba when she lied about her age to join the military?",options:["14","16","18","21"],answer:"16"},
  {question:"What human emotional trait forms the basis of Nora's frightening ability?",options:["Her panicky nature","Her cold arrogance","Her deep empathy","Her unyielding calm"],answer:"Her panicky nature"},
  {question:"What childhood dream drove Mantie to join the military?",options:["Flying among the stars","Slaying dangerous pirate fleets","Designing electronic circuitry","Acquiring massive wealth"],answer:"Flying among the stars"},
  {question:"Which institution gave Lawrence a full scholarship for his math skills?",options:["Galactic Weapon College","Supreme Science Academy","Command College Engineering Class","Galaxy Technical College"],answer:"Galactic Weapon College"},
  {question:"What distinct metaphor describes Evi's unusually cold eyes?",options:["Ice pools","Black holes","Laser beams","Frozen stars"],answer:"Ice pools"},
  {question:"Who are fondly known as the 'Twin Heroes' in the galaxy lore?",options:["Gastaf and Todd","Wayne and Sandora","Nick and Jerome","Stani and Aileen"],answer:"Gastaf and Todd"},
  {question:"What academic position did Rafia hold prior to the great space war?",options:["Engineering researcher at the supreme science academy","Trajectory professor at the weapon college","Adviser to the command college board","Chief medical officer"],answer:"Engineering researcher at the supreme science academy"},
  {question:"What descriptive nickname belongs to Murphy Lawson?",options:["Black Hole","Witchdoctor","Twin Torpedo","Brilliant Strategist"],answer:"Black Hole"},
  {question:"What historic event forged Javal's galaxy reputation?",options:["Repelling a pirate fleet that threatened his homeworld","Graduating top of the supreme weapon college","Escaping a wolf pack den unscathed","Defeating Red Beard's armada on a school dare"],answer:"Repelling a pirate fleet that threatened his homeworld"},
];